### ISSUE TITLE
Where are forms actually saved?

### ISSUE THREAD

**Issue by Gitoffthelawn** [lutostag/webextension-formsave#3]
Where are the forms actually saved?

When are they automatically cleared?

**Comment by lutostag** [comment]
Textareas are saved in local storage. You should be able to access them by clicking on the icon. 

They are not automatically cleared at the moment -- (the code has landed but hasn't gone through review on addons.mozilla.org, when it does there is an option you can toggle in `about:addons`).

In the current release there is a bug that the `clear` and `clear all` buttons do not work unfortunately. That is fixed with the release in the queue.

Does that help answer your question?

**Comment by Gitoffthelawn** [comment]
Very much so, thank you.  What is the AMO queue position?

**Comment by lutostag** [comment]
Queue Position: 119 of 283
Initially submitted on March 29, 2017 It hasn't moved at all since then unfortunately :(

**Comment by Gitoffthelawn** [comment]
You might want to ping Mozilla... sometimes that gets it moving up the queue.

**Comment by lutostag** [comment]
Thanks for the suggestion. The latest version has been released (0.9.5). Which fixes the deletion issue. It seems like the saved forms from the previous version 0.9.3 will not show up if clicked on. So you should 'clear all' and it should work from here on out. I will cut a 0.9.6 release sometime this weekend with that `about:addons` setting, seems like it didn't make it into the previous 0.9.5. Sorry about that.

**Comment by Gitoffthelawn** [comment]
Thanks!

**Comment by lutostag** [comment]
Latest version with addon options to auto-expire has hit the store. 
![image](https://cloud.githubusercontent.com/assets/962625/26380469/65c6a300-3fe4-11e7-8694-dd7e05a4ba41.png)

Let me know if that's not what you were expecting.

**Comment by Gitoffthelawn** [comment]
Thanks!  I'll take a look! :)
