### ISSUE TITLE
Timer Option 

### ISSUE THREAD

**Issue by Taurean75** [lutostag/webextension-formsave#6]
Please add a delay / timer option to specify the number of seconds that the extension has to wait before saving form entries. Thanks.

**Comment by lutostag** [comment]
@Taurean75

Thanks for filling an issue. Sounds like a reasonable request.

But can I get just a bit more information?

Currently a trigger is set to update on changes to a textareas, so that when it changes it happens immediately (where is waits for 400ms of inactivity to save). Do you mean you only want to only save every say 5 minutes or so (user-configurable), or is there something else you mean?

I guess what I'm asking is when you would use it and how you would expect it to work.

Any further clarifications would be helpful to make sure the implementation would meet your needs.

**Comment by Taurean75** [comment]
An user-configurable time interval is what I meant. It saves too often right now.

Thanks.

**Comment by lutostag** [comment]
Just added this in. Gonna run it for a few days on my end to test more before I release the latest version with it included.

Screenshot of it in action with my test build.

![screenshot from 2017-12-04 16-07-28](https://user-images.githubusercontent.com/962625/33578805-5b98dd5e-d90d-11e7-8d67-e83da8f56a6e.png)

Hope this is what you were looking for!

**Comment by Taurean75** [comment]
Great, thanks!
